image: debian:jessie

compile:
  when: manual
  script:
    - apt-get update
    - apt-get install -y -q --no-install-recommends make wget multistrap fakeroot mtd-utils android-tools-fsutils u-boot-tools cpio git ca-certificates
    - make WGET_OPTS='--progress=dot:giga'
  artifacts:
    paths:
      - flash.tar.gz
      - rootfs.ubi.sparse
      - rescue.tar.gz
