image: debian:jessie

compile:
  when: manual
  script:
    - apt-get update
    - apt-get install -y make wget multistrap fakeroot mtd-utils android-tools-fsutils u-boot-tools cpio git gcc python-lzo python3 squashfs-tools
    - make WGET_OPTS='--progress=dot:giga'
  artifacts:
    paths:
      - flash.tar.gz
      - rootfs.ubi.sparse
      - rescue.tar.gz
      - prebuilt/pocket44_01.squashfs
